sudo: false
language: go
go:
  - 1.10.x

os:
  - linux
  - osx

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

before_install:
  - go get -u golang.org/x/vgo

install:
  - vgo list -m -u

script:
  # - diff -u <(echo -n) <(gofmt -d -s .)
  # - vgo tool vet .
  # - vgo test -v -race ./...
  - yarn version-darwin-amd64

notifications:
  email:
    - silas.baronda@gmail.com