sudo: false
language: go
go:
  - 1.10.x

matrix:
  include:
    - os: linux
      before_install:
        - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
        - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        - sudo apt-get update && sudo apt-get install yarn
        - sudo add-apt-repository ppa:webkit-team/ppa -y
        - sudo apt-get update
        - sudo apt-get install libwebkit2gtk-4.0-dev -y
      script:
        - yarn version-darwin-linux-amd64
    - os: osx
      osx_image: xcode8.3
      script:
        - yarn version-darwin-linux-amd64
  # fast_finish: true

install:
  - go get -x -u github.com/jteeuwen/go-bindata/...
  - go get -x -u golang.org/x/vgo
  - vgo list -m -u
  - yarn install

notifications:
  email:
    - silas.baronda@gmail.com