sudo: false
language: go
go:
  - 1.10.x

matrix:
  include:
    - os: linux
      before_install:
        - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
        - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        - sudo apt-get update && sudo apt-get install yarn
        - sudo add-apt-repository ppa:webkit-team/ppa -y
        - sudo apt-get update
        - sudo apt-get install libwebkit2gtk-4.0-dev -y
    - os: osx
      osx_image: xcode8.3
  # fast_finish: true

before_install:
  - go get -u golang.org/x/vgo

install:
  - vgo list -m -u

script:
  # - diff -u <(echo -n) <(gofmt -d -s .)
  # - vgo tool vet .
  # - vgo test -v -race ./...
  - yarn version-darwin-amd64

notifications:
  email:
    - silas.baronda@gmail.com