sudo: false
language: go
go:
  - 1.10.x

os:
  - linux
  - osx

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

before_install:
  - go get -u golang.org/x/vgo

install:
  - vgo get

script:
  - diff -u <(echo -n) <(gofmt -d -s .)
  - vgo tool vet .
  - vgo test -v -race ./...

notifications:
  email:
    - silas.baronda@gmail.com